### ISSUE TITLE
希望能自定义SOCKSPort的数量

### ISSUE THREAD

**Issue by zephyr-y** [Ridter/TorProxy#2]
目前是固定的10个，希望能作为参数自定义。
或者手动修改，手动修改都有哪些地方需要修改，请作者大佬指点

**Comment by Ridter** [comment]
可以手动在Torrc文件中，增加新的SOCKSPort，然后再修改[config.json](https://github.com/Ridter/TorProxy/blob/main/config/config.json)，增加servers的list，对应增加新的代理端口即可。
